use_for: "Tensorflow"
directory: "data/raw/train-image.hdf5"
batch_size: 32
image_size: [128, 128]
seed: 42
train_test_split: [0.8, 0.2]
save_dataset_path: data/processed/dataset
train_ds_len: 1000
test_ds_len: 100
